# Generated by Django 4.1 on 2024-02-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_ingredient_cheese_alter_ingredient_meat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='cheese',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='meat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='salad',
            field=models.IntegerField(default=0),
        ),
    ]
